version: '3'
services:
#  web:
#    build: .
#    ports:
#      - 8000:8000
#    depends_on:
#      - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}